services:
  postgres-db:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "$POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT"
    environment:
      POSTGRES_USER: $USER
      POSTGRES_PASSWORD: $PASSWORD
      POSTGRES_DB: $POSTGRES_DB

  pg-admin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres-db
    env_file: ./.env
    ports:
      - "$PGADMIN_LOCAL_PORT:$PGADMIN_DOCKER_PORT"
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_CONFIG_SERVER_MODE=False
    entrypoint: >
      /bin/sh -c '
      chmod 600 /tmp/pgpass;
      /entrypoint.sh'
    user: root
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /tmp/pgpass
      - source: preferences.json
        target: /pgadmin4/preferences.json

  minio:
    image: minio/minio
    restart: unless-stopped
    depends_on:
      - postgres-db
    env_file: ./.env
    ports:
      - "$MINIO_SERVER_PORT:$MINIO_SERVER_PORT"
      - "$MINIO_CONSOLE_PORT:$MINIO_CONSOLE_PORT"
    environment:
      - MINIO_ROOT_USER=$USER
      - MINIO_ROOT_PASSWORD=$PASSWORD
      - MINIO_UPDATE=off
    volumes:
      - ./backend/minio/data:/data
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"

  minio-setup:
    image: minio/mc
    depends_on:
        - minio
    restart: no
    entrypoint: >
      /bin/sh -c '
        /usr/bin/mc alias set minio http://minio:${MINIO_SERVER_PORT} ${USER} ${PASSWORD}              # setup Minio client
        /usr/bin/mc mb minio/${MINIO_BUCKET} || true                                                   # create bucket
        /usr/bin/mc anonymous set public minio/${MINIO_BUCKET}                                         # make the bucket public
        /usr/bin/mc admin user svcacct add --access-key "${MINIO_ACCESS_KEY}" --secret-key "${MINIO_SECRET_KEY}" minio ${USER}          # add access and secret key
        exit 0;
      '

configs:
  pgpass:
    content: postgres-db:$POSTGRESDB_DOCKER_PORT:*:$USER:$PASSWORD
  servers.json:
    content: >-
      {
        "Servers": {
          "1": {
            "Name": "Code Node Server",
            "Group": "Servers",
            "Port": ${POSTGRESDB_DOCKER_PORT},
            "Username": "${USER}",
            "Host": "postgres-db",
            "MaintenanceDB": "postgres",
            "PassFile": "/tmp/pgpass",
            "SSLMode": "prefer"
          }
        }
      }
  preferences.json:
    content: >-
      {
        "preferences": {
          "misc:themes:theme": "dark"
        }
      }